In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [37]:

import pandas as pd

data = {
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30]
}

df = pd.DataFrame(data)

print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [38]:
import pandas as pd
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name','Age'])

In [39]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [40]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [42]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [43]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [44]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [45]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [46]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [47]:
df[df['Age'] >25]

  Name  Age
1  Bob   30

In [48]:
df['Gender'] = ['F', 'M']

In [49]:
#df.drop('Age', axis=1, inplace=True)

In [50]:
df.isnull()

    Name    Age  Gender
0  False  False   False
1  False  False   False

In [51]:
df.dropna()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [52]:
df.fillna(0)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [53]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [57]:
import pandas as pd

df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'key': [1, 2, 3],
    'Age': [25, 30, 35]
})

pd.merge(df1, df2, on='key')

   key     Name  Age
0    1    Alice   25
1    2      Bob   30
2    3  Charlie   35

In [60]:
df1.join(df2, lsuffix='_left', rsuffix='_right')

   key_left     Name  key_right  Age
0         1    Alice          1   25
1         2      Bob          2   30
2         3  Charlie          3   35

In [65]:
df.to_csv('data.csv', index=False)

In [66]:
df = pd.read_csv('data.csv')
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [68]:
df.to_csv('output.csv', index=False)

In [69]:
df.sort_values('Age')

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [70]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
Name: Age, dtype: int64

In [71]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [72]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64